[book]
authors = ["commitr"]
language = "en"
src = "src"
title = "A Century of the Names and Scantilings of Such Inventions as at Present I Can Call to Mind to Have Tried and Perfected, which (my former notes being lost) I have, at the insistence of a powerful friend, endeavored now in the year 2022, to set these down in such a way as may sufficiently instruct me to put any of them in practice"
